name: Publish and Intimate VS Code

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          if npm view kschema-api-gen-endpointsjs@$CURRENT_VERSION version >/dev/null 2>&1; then
            echo "Version $CURRENT_VERSION is already published on npm. Skipping publication."
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: keshavsoft/vs-code-ext-express-api-gen-endpoints
          event-type: kschema_published
